### PR TITLE
#57 Migrate package names to org.starchartlabs.*

### PR DESCRIPTION
**Pull request by romeara**

### CODE REVIEW

**Comment by romeara** [comment]
@nickavv Did I miss a qualified name referenced by UI tests or something?

**Comment by nickavv** [comment]
Huh, not that I know of. Do those tests pass locally still?

**Comment by romeara** [comment]
`./gradlew clean build` passed before I pushed...

**Comment by romeara** [comment]
@nickavv Fixed it trying to run a couple tests, still doing a weird thing - care to take a look?

**Comment by romeara** [comment]
Will retry once UI switchover is complete

**Pull request closed without merging**
